"""SPEC-0018 Stage Purity: AcquisitionExecutionStage.

Executes the acquisition plan generated by SourceSelectionStage to gather raw observations.
Maintains strict separation between raw observations and fused evidence.
"""

from __future__ import annotations

from typing import Any, Dict, List

from ape.intelligence.research.providers.audience import HeuristicAudienceProvider
from ape.intelligence.research.providers.hackernews import HackerNewsResearchProvider
from ape.pipeline.contracts import (
    PipelineContext,
    PipelineStage,
    StageResult,
    StageStatus,
)


class AcquisitionExecutionStage(PipelineStage):
    """Pure pipeline stage that executes the acquisition plan to collect raw observations."""

    def __init__(self, offline: bool = False) -> None:
        self._offline = offline
        self._providers = {
            "HackerNews": HackerNewsResearchProvider(offline=offline),
            "AudienceHeuristics": HeuristicAudienceProvider(),
        }

    @property
    def name(self) -> str:
        return "acquisition_execution"

    def execute(
        self,
        context: PipelineContext,
        previous_results: List[StageResult],
    ) -> StageResult:
        """Executes acquisition plan, collecting raw observations from configured providers."""
        topic = context.topic_slug.strip()
        if not topic:
            return StageResult(
                stage_name=self.name,
                status=StageStatus.FAILED,
                error="Topic slug cannot be empty for AcquisitionExecutionStage",
            )

        # Retrieve acquisition plan from previous stage
        acquisition_plan = {}
        for prev in previous_results:
            if prev.stage_name == "source_selection" and prev.status == StageStatus.SUCCESS:
                acquisition_plan = prev.output_data
                break

        selected_sources = acquisition_plan.get(
            "selected_sources", ["HackerNews", "AudienceHeuristics"]
        )

        raw_observations: List[Dict[str, Any]] = []
        combined_signals: Dict[str, Any] = {}

        for source_name in selected_sources:
            provider = self._providers.get(source_name)
            if provider:
                try:
                    signals = provider.fetch_signals(topic)
                    observation_entry = {
                        "source": source_name,
                        "status": "SUCCESS",
                        "signals": signals,
                    }
                    raw_observations.append(observation_entry)

                    # Merge signals for downstream pipeline consumption
                    for k, v in signals.items():
                        if isinstance(v, list):
                            existing = combined_signals.setdefault(k, [])
                            if isinstance(existing, list):
                                existing.extend(v)
                        elif isinstance(v, (int, float)):
                            if k in combined_signals:
                                combined_signals[k] = min(combined_signals[k], v)
                            else:
                                combined_signals[k] = v
                        else:
                            combined_signals[k] = v
                except Exception as exc:
                    raw_observations.append({
                        "source": source_name,
                        "status": "ERROR",
                        "error": str(exc),
                    })

        output_data = {
            "topic": topic,
            "observation_count": len(raw_observations),
            "raw_observations": raw_observations,
            "combined_signals": combined_signals,
        }

        evidence = {
            "executed_sources": [obs["source"] for obs in raw_observations],
            "successful_acquisitions": len(
                [obs for obs in raw_observations if obs["status"] == "SUCCESS"]
            ),
        }

        return StageResult(
            stage_name=self.name,
            status=StageStatus.SUCCESS,
            output_data=output_data,
            evidence=evidence,
        )
