from __future__ import annotations

from typing import Any, Dict, List, Optional


class EvidenceTaxonomyModel:
    """
    R&D Evidence Taxonomy & Quality Model.
    Formalizes the 11 epistemic evidence categories, distinguishes Stated vs Observed behaviors,
    evaluates Channel & Source Diversity, and replaces misleading numeric confidence percentages
    with multi-dimensional epistemic coverage metrics.
    """

    CATEGORIES = {
        "OBSERVED_BEHAVIOR": {
            "definition": "User reproduced setup problem or executed CLI binary.",
            "epistemic_weight": 1.0,
            "can_trigger_GO": True,
            "can_trigger_NOGO": False,
            "requires_corroboration": True,
        },
        "OBSERVED_PAYMENT": {
            "definition": "User has active SaaS/tool spend ($/month) for current problem.",
            "epistemic_weight": 1.0,
            "can_trigger_GO": True,
            "can_trigger_NOGO": False,
            "requires_corroboration": True,
        },
        "OBSERVED_USAGE": {
            "definition": "User maintains an active manual workaround daily/weekly.",
            "epistemic_weight": 0.8,
            "can_trigger_GO": False,
            "can_trigger_NOGO": False,
            "requires_corroboration": True,
        },
        "STATED_INTENT": {
            "definition": "User survey response stating hypothetical payment ('Would pay $29') or trial interest.",
            "epistemic_weight": 0.3,
            "can_trigger_GO": False,
            "can_trigger_NOGO": False,
            "requires_corroboration": True,
        },
        "REPORTED_BEHAVIOR": {
            "definition": "User describes past manual labor hours during direct interview.",
            "epistemic_weight": 0.6,
            "can_trigger_GO": False,
            "can_trigger_NOGO": False,
            "requires_corroboration": True,
        },
        "NEGATIVE_EVIDENCE": {
            "definition": "User explicitly denies problem ('don't have problem', 'won't pay', 'current tools fine').",
            "epistemic_weight": 1.0,
            "can_trigger_GO": False,
            "can_trigger_NOGO": True,
            "requires_corroboration": False,
        },
        "UNKNOWN": {
            "definition": "Missing survey fields or zero responses logged.",
            "epistemic_weight": 0.0,
            "can_trigger_GO": False,
            "can_trigger_NOGO": False,
            "requires_corroboration": False,
        },
        "INFERRED": {
            "definition": "Analytical hypothesis or conclusion generated by prior internal APE reports.",
            "epistemic_weight": 0.0,
            "can_trigger_GO": False,
            "can_trigger_NOGO": False,
            "requires_corroboration": False,
        },
        "PROVISIONAL_THRESHOLD": {
            "definition": "Internal candidate heuristic count (e.g. 10 users). Not a scientific market law.",
            "epistemic_weight": 0.0,
            "can_trigger_GO": False,
            "can_trigger_NOGO": False,
            "requires_corroboration": False,
        },
        "SYNTHETIC": {
            "definition": "AI-generated bot response (is_synthetic=true). Ingestion rejected.",
            "epistemic_weight": 0.0,
            "can_trigger_GO": False,
            "can_trigger_NOGO": True,
            "requires_corroboration": False,
        },
        "TEST_FIXTURE": {
            "definition": "Controlled test payload used in-memory for simulation testing.",
            "epistemic_weight": 0.0,
            "can_trigger_GO": False,
            "can_trigger_NOGO": False,
            "requires_corroboration": False,
        },
    }

    def evaluate_model(
        self,
        opportunity: str,
        user_responses: List[dict[str, Any]]
    ) -> dict[str, Any]:
        real_count = len(user_responses)

        # Multi-dimensional Epistemic Coverage Metrics (Replacing single fake % confidence)
        epistemic_metrics = {
            "evidence_completeness": "0%" if real_count == 0 else f"{min(100, real_count * 10)}%",
            "evidence_quality": "UNTESTED" if real_count == 0 else "PARTIAL",
            "evidence_diversity": "0_CHANNELS" if real_count == 0 else f"{len(set(r.get('source', 'unknown') for r in user_responses))}_CHANNELS",
            "hypothesis_coverage": "H1: UNKNOWN, H2: UNKNOWN, H3: UNKNOWN" if real_count == 0 else "EVALUATED",
            "epistemic_uncertainty": "HIGH (0 real user responses logged)",
        }

        return {
            "experiment": "ORION-044",
            "status": "TAXONOMY_DESIGN_COMPLETE",
            "opportunity": opportunity,
            "observed_real_user_count": real_count,
            "categories": self.CATEGORIES,
            "epistemic_metrics": epistemic_metrics,
            "confidence_score_critique": (
                "Single numeric confidence scores (e.g. 35% at 0 responses) create false precision. "
                "APE MUST use multi-dimensional coverage metrics (completeness, quality, diversity, coverage, uncertainty) "
                "to clearly convey epistemic risk to human engineers."
            ),
        }
