"""
AgentNode Protocol & Role-Based Agent Implementations — ORION-116 Specification.
Provides AgentRole enum, AgentNode Protocol, and concrete Architect, Coder, QA, and Auditor agent nodes.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Protocol, runtime_checkable


class AgentRole(str, Enum):
    """Multi-agent swarm role classification."""
    ARCHITECT = "architect"
    CODER = "coder"
    QA = "qa"
    AUDITOR = "auditor"
    PM = "pm"


@dataclass(frozen=True)
class SwarmTask:
    """Immutable task payload dispatched to an AgentNode."""
    task_id: str
    goal: str
    target_role: AgentRole
    context_data: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AgentResponse:
    """Standardized response produced by an AgentNode."""
    agent_id: str
    role: AgentRole
    success: bool
    output_text: str
    artifacts_produced: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@runtime_checkable
class AgentNode(Protocol):
    """Canonical AgentNode interface for in-memory multi-agent swarm collaboration."""
    agent_id: str
    role: AgentRole

    def execute_task(self, task: SwarmTask, shared_memory: Any) -> AgentResponse:
        ...


class BaseAgentNode:
    """Base agent node implementation with default execution framing."""

    def __init__(self, agent_id: str, role: AgentRole) -> None:
        self.agent_id = agent_id
        self.role = role

    def execute_task(self, task: SwarmTask, shared_memory: Any) -> AgentResponse:
        shared_memory.set(f"task_output_{self.role.value}", f"Output for task '{task.goal}' generated by {self.agent_id}")
        return AgentResponse(
            agent_id=self.agent_id,
            role=self.role,
            success=True,
            output_text=f"[{self.role.upper()} Completed] {task.goal}",
        )


class ArchitectAgentNode(BaseAgentNode):
    """Architect agent responsible for system blueprint and DAG design."""

    def __init__(self, agent_id: str = "agent_architect") -> None:
        super().__init__(agent_id, AgentRole.ARCHITECT)


class CoderAgentNode(BaseAgentNode):
    """Coder agent responsible for module and software implementation."""

    def __init__(self, agent_id: str = "agent_coder") -> None:
        super().__init__(agent_id, AgentRole.CODER)


class QAAgentNode(BaseAgentNode):
    """QA agent responsible for test generation and quality verification."""

    def __init__(self, agent_id: str = "agent_qa") -> None:
        super().__init__(agent_id, AgentRole.QA)


class AuditorAgentNode(BaseAgentNode):
    """Auditor agent responsible for security, governance, and compliance auditing."""

    def __init__(self, agent_id: str = "agent_auditor") -> None:
        super().__init__(agent_id, AgentRole.AUDITOR)
