"""
LLM Provider implementations for APE.

Supports:
- Ollama (local, free, no API key)
- OpenAI API (cloud, requires key)
- Deterministic fallback (no LLM, template-based — current default)
"""
from __future__ import annotations

import json
import logging
import urllib.request
from typing import Any, Dict, Optional

from ape.intelligence.roadmap.llm import PlannerModel

logger = logging.getLogger(__name__)


class OllamaProvider(PlannerModel):
    """
    Ollama local LLM provider.
    Connects to Ollama's OpenAI-compatible API at localhost:11434.
    No API key required.
    """

    def __init__(
        self,
        model: str = "codellama",
        base_url: str = "http://localhost:11434",
        timeout: int = 120,
    ) -> None:
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout

    def is_available(self) -> bool:
        """Check if Ollama is running and the model is available."""
        try:
            req = urllib.request.Request(f"{self.base_url}/api/tags", method="GET")
            with urllib.request.urlopen(req, timeout=5) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                models = [m.get("name", "").split(":")[0] for m in data.get("models", [])]
                return self.model in models or f"{self.model}:latest" in [m.get("name", "") for m in data.get("models", [])]
        except Exception:
            return False

    def generate(self, prompt: str, system_message: str, schema: dict) -> Dict[str, Any]:
        """Generate structured JSON via Ollama's OpenAI-compatible chat endpoint."""
        url = f"{self.base_url}/v1/chat/completions"

        schema_str = json.dumps(schema, indent=2)
        system_with_schema = (
            f"{system_message}\n\n"
            "You MUST return your response as a valid JSON object matching this schema:\n"
            f"{schema_str}\n\n"
            "Return ONLY raw JSON. No markdown, no explanation, no code fences."
        )

        data = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_with_schema},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.2,
            "stream": False,
        }

        req = urllib.request.Request(
            url,
            data=json.dumps(data).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as response:
                result = json.loads(response.read().decode("utf-8"))
                content = result["choices"][0]["message"]["content"].strip()
                content = _strip_markdown_fences(content)
                return json.loads(content)
        except Exception as e:
            raise RuntimeError(f"Ollama API Error ({self.base_url}): {e}") from e


class DeterministicProvider(PlannerModel):
    """
    Zero-LLM fallback provider.
    Generates structured responses deterministically from task metadata.
    Used when no LLM is available — ensures APE never hard-fails on missing LLM.
    """

    def generate(self, prompt: str, system_message: str, schema: dict) -> Dict[str, Any]:
        """Parse task info from prompt and generate deterministic action proposal."""
        # Extract deliverable paths from prompt
        deliverables = []
        for line in prompt.split("\n"):
            if "Required Deliverables:" in line:
                parts = line.split(":", 1)[1].strip()
                deliverables = [p.strip() for p in parts.split(",") if p.strip()]
                break

        # Determine action based on deliverables
        if deliverables:
            target = deliverables[0]
            if target.endswith(".py"):
                content = (
                    '"""Auto-generated module."""\n\n'
                    'def main() -> dict:\n'
                    '    return {"status": "ok", "message": "Generated by APE"}\n\n'
                    'if __name__ == "__main__":\n'
                    '    print(main())\n'
                )
                return {
                    "thought": f"Creating Python deliverable: {target}",
                    "action": "create_file",
                    "params": {"path": target, "content": content},
                }
            else:
                return {
                    "thought": f"Creating deliverable: {target}",
                    "action": "create_file",
                    "params": {"path": target, "content": f"# Generated: {target}\n"},
                }

        return {
            "thought": "No specific deliverables found, running analysis.",
            "action": "analyze",
            "params": {},
        }


def auto_detect_provider(
    preferred_model: str = "codellama",
    openai_api_key: Optional[str] = None,
) -> PlannerModel:
    """
    Auto-detect the best available LLM provider.
    Priority: Ollama (local) > OpenAI (cloud) > Deterministic (fallback).
    """
    # 1. Try Ollama
    ollama = OllamaProvider(model=preferred_model)
    if ollama.is_available():
        logger.info("LLM Provider: Ollama (%s) detected at localhost:11434", preferred_model)
        return ollama

    # 2. Try OpenAI
    if openai_api_key:
        from ape.intelligence.roadmap.llm import OpenAICompatibleProvider
        logger.info("LLM Provider: OpenAI API")
        return OpenAICompatibleProvider(api_key=openai_api_key, model="gpt-4o")

    # 3. Fallback
    logger.info("LLM Provider: Deterministic fallback (no LLM available)")
    return DeterministicProvider()


def _strip_markdown_fences(text: str) -> str:
    """Strip markdown code fences from LLM responses."""
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    return text.strip()
