"""
GitHub Integration Engine — ORION-103 Reality Check Specification.
Processes webhooks and executes REAL GitHub REST API v3 calls for branch creation and Pull Requests.
Tags execution mode explicitly as REAL or SIMULATED.
"""

import hashlib
import hmac
import json
import os
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class GitHubEvent:
    """Parsed GitHub webhook event packet."""
    event_type: str  # pull_request, push, issue_comment
    action: str  # opened, synchronize, closed
    repo_name: str
    pr_number: Optional[int]
    commit_sha: str
    payload: Dict[str, Any]


class GitHubWebhookHandler:
    """Processes GitHub webhooks and executes REAL GitHub API actions."""

    def __init__(self, secret: str = "ape_github_webhook_secret_2026", token: Optional[str] = None) -> None:
        self.secret = secret.encode("utf-8")
        self.token = token or os.environ.get("GITHUB_TOKEN") or os.environ.get("APE_GITHUB_TOKEN")

    def verify_signature(self, body_bytes: bytes, signature_header: str) -> bool:
        """Verify HMAC SHA-256 signature from GitHub X-Hub-Signature-256 header."""
        if not signature_header.startswith("sha256="):
            return False
        expected_sig = hmac.new(self.secret, body_bytes, hashlib.sha256).hexdigest()
        provided_sig = signature_header[len("sha256="):]
        return hmac.compare_digest(provided_sig, expected_sig)

    def parse_event(self, event_type: str, raw_json: str) -> GitHubEvent:
        """Parse raw GitHub webhook JSON into GitHubEvent."""
        data = json.loads(raw_json)
        repo_name = data.get("repository", {}).get("full_name", "unknown/repo")
        pr_number = data.get("pull_request", {}).get("number")
        commit_sha = data.get("pull_request", {}).get("head", {}).get("sha") or data.get("after", "head_sha")

        return GitHubEvent(
            event_type=event_type,
            action=data.get("action", "push"),
            repo_name=repo_name,
            pr_number=pr_number,
            commit_sha=commit_sha,
            payload=data,
        )

    def create_pull_request(self, repo_name: str, branch_name: str, title: str, head_branch: str = "main") -> Dict[str, Any]:
        """
        Create GitHub Pull Request.
        Executes REAL GitHub REST API v3 request if token is set, else returns SIMULATED mode.
        """
        if self.token:
            url = f"https://api.github.com/repos/{repo_name}/pulls"
            headers = {
                "Authorization": f"Bearer {self.token}",
                "Accept": "application/vnd.github+json",
                "User-Agent": "APE-Platform-Engine/1.0",
                "Content-Type": "application/json",
            }
            body = json.dumps({
                "title": title,
                "head": branch_name,
                "base": head_branch,
                "body": "Automated Pull Request generated by APE v1.0 Quality OS.",
            }).encode("utf-8")

            req = urllib.request.Request(url, data=body, headers=headers, method="POST")
            try:
                with urllib.request.urlopen(req) as resp:
                    res_data = json.loads(resp.read().decode("utf-8"))
                    return {
                        "integration_mode": "REAL",
                        "pr_number": res_data.get("number"),
                        "pr_url": res_data.get("html_url"),
                        "status": "OPEN",
                    }
            except Exception as exc:
                return {
                    "integration_mode": "SIMULATED",
                    "pr_number": 42,
                    "pr_url": f"https://github.com/{repo_name}/pull/42 (SIMULATED)",
                    "status": "OPEN",
                    "error": str(exc),
                }

        return {
            "integration_mode": "SIMULATED",
            "pr_number": 42,
            "pr_url": f"https://github.com/{repo_name}/pull/42 (SIMULATED)",
            "status": "OPEN",
        }
